name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:

defaults:
  run:
    working-directory: App
    
jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: checkout code
    - uses: actions/checkout@v2
    - name: login to docker hub
      run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
    - name: Docker Buildx
      uses: crazy-max/ghaction-docker-buildx@v3.3.0
    - name: puild and push Docker images
      run: docker buildx build --push \
           --file Dockerfile.multi-arch \
           --tag teheran/mariner \
           --platform linux/amd64,linux/arm/v7 .
